---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cluster-test-one
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cluster-test-one

  template:
    metadata:
      labels:
        project: cluster-test
        app: cluster-test-one
    spec:
      containers:
        - name: one
          image: 10.102.57.234/cluster-test/one-rel
          env:
            - name: RELEASE_COOKIE
              value: "dwkdwaijdoaw"
            - name: RELEASE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ["/opt/app/bin/one"]
          args: ["start"]

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cluster-test-two
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cluster-test-two

  template:
    metadata:
      labels:
        project: cluster-test
        app: cluster-test-two
    spec:
      containers:
        - name: two
          image: 10.102.57.234/cluster-test/two-rel
          env:
            - name: RELEASE_COOKIE
              value: "dwkdwaijdoaw"
            - name: RELEASE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ["/opt/app/bin/two"]
          args: ["start"]

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cluster-test-three
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cluster-test-three

  template:
    metadata:
      labels:
        project: cluster-test
        app: cluster-test-three
    spec:
      containers:
        - name: three
          image: 10.102.57.234/cluster-test/three-rel
          ports:
            - containerPort: 6000
          env:
            - name: PORT
              value: "6000"
            - name: RELEASE_COOKIE
              value: "dwkdwaijdoaw"
            - name: RELEASE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ["/opt/app/bin/three"]
          args: ["start"]

---
kind: Service
apiVersion: v1
metadata:
  name: cluster-nodes-one
  namespace: default
spec:
  clusterIP: None
  selector:
    app: cluster-test-one
  ports:
    - name: epmd
      port: 4369

---
kind: Service
apiVersion: v1
metadata:
  name: cluster-nodes-two
  namespace: default
spec:
  clusterIP: None
  selector:
    app: cluster-test-two
  ports:
    - name: epmd
      port: 4369

---
kind: Service
apiVersion: v1
metadata:
  name: cluster-nodes-three
  namespace: default
spec:
  clusterIP: None
  selector:
    app: cluster-test-three
  ports:
    - name: epmd
      port: 4369

---
kind: Service
apiVersion: v1
metadata:
  name: cluster-test-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: cluster-test-three
  ports:
    - name: http
      port: 6000
      targetPort: 6000
